const PRODUCTS = [
  {
    id: 1,
    name: "New Balance 530",
    price: "109.90",
    image: require("../src/images/nb530.jpg"),
    brand: "New Balance",
  },
  {
    id: 2,
    name: "New Balance 997",
    price: "119.90",
    image: require("../src/images/nb997.jpg"),
    brand: "New Balance",
  },
  {
    id: 3,
    name: "Nike Storm-Fit ADV Tech Pack Gore-Tex Jacket",
    price: "349.90",
    image: require("../src/images/nikevest.jpg"),
    brand: "Nike",
  },
  {
    id: 4,
    name: "Lacoste G80 Club",
    price: "149.90",
    image: require("../src/images/lacosteg80.jpg"),
    brand: "Lacoste",
  },
  {
    id: 5,
    name: "Converse Chuck 70 High",
    price: "99.90",
    image: require("../src/images/conversechuck70.jpg"),
    brand: "Converse",
  },
  {
    id: 6,
    name: "Converse Chuck 70 High",
    price: "99.90",
    image: require("../src/images/conversechuck70color.jpg"),
    brand: "Converse",
  },
  {
    id: 7,
    name: "Asics Gel-1090",
    price: "129.90",
    image: require("../src/images/asicsgel1090.jpg"),
    brand: "Asics",
  },
  {
    id: 8,
    name: "Wmns Asics Gel-Nimbus 25",
    price: "229.90",
    image: require("../src/images/Wmns Asics Gel-Nimbus 25.jpg"),
    brand: "Asics",
  },
  {
    id: 9,
    name: "Nike Air Max 1 Premium «Crepe»",
    price: "189.90",
    image: require("../src/images/Nike Air Max 1 Premium «Crepe».jpg"),
    brand: "Nike",
  },
  {
    id: 10,
    name: "Wmns Air Jordan 1 Retro OG «Reverse Laney»",
    price: "189.90",
    image: require("../src/images/Wmns Air Jordan 1 Retro High OG «Reverse Laney».jpg"),
    brand: "Nike",
  },
  {
    id: 11,
    name: "Air Jordan 1 Mid SE Craft «Inside Out»",
    price: "149.90",
    image: require("../src/images/Air Jordan 1 Mid SE Craft «Inside Out».jpg"),
    brand: "Air jordan",
  },
  {
    id: 12,
    name: "Air Jordan Legacy 312 «Rookie Of The Year»",
    price: "169.90",
    image: require("../src/images/Air Jordan Legacy 312 «Rookie Of The Year».jpg"),
    brand: "Air Jordan",
  },
  {
    id: 13,
    name: "Lacoste Short",
    price: "109.90",
    image: require("../src/images/Lacoste Short.jpg"),
    brand: "Lacoste",
  },
  {
    id: 14,
    name: "Adidas Gazelle Indoor",
    price: "119.90",
    image: require("../src/images/Adidas Gazelle Indoor.jpg"),
    brand: "Adidas",
  },
  {
    id: 15,
    name: "Karhu Fusion 2.0",
    price: "149.90",
    image: require("../src/images/Karhu Fusion 2.0.jpg"),
    brand: "Karshu",
  },
];
export default PRODUCTS;
